# Generated by Django 3.1 on 2020-09-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0002_auto_20200914_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='blocks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crossword',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
