# Generated by Django 4.0.3 on 2022-03-23 19:05

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('puzzles', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='elapsed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='reveal_clue_nums',
            field=models.CharField(max_length=100, null=True, validators=[
                django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid',
                                                      message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='session',
            name='solved_clue_nums',
            field=models.CharField(max_length=100, null=True, validators=[
                django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid',
                                                      message='Enter only digits separated by commas.')]),
        ),
    ]
