# Generated by Django 4.0.3 on 2022-03-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_rename_reveal_clue_nums_session_revealed_clue_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_complete',
        ),
    ]
