# Generated by Django 3.1 on 2020-10-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_auto_20200929_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossword',
            old_name='size',
            new_name='grid_size',
        ),
    ]
