# Generated by Django 4.0.3 on 2022-03-24 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0005_remove_session_is_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='PuzzleSession',
        ),
    ]
