# Generated by Django 4.0.3 on 2022-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('puzzles', '0006_rename_session_puzzlesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlesession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
