# Generated by Django 3.1 on 2020-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_auto_20201001_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crossword',
            name='grid_content',
            field=models.TextField(default=''),
        ),
    ]
