# Generated by Django 3.1 on 2020-10-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_auto_20201019_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossword',
            old_name='grid_content',
            new_name='across_words',
        ),
        migrations.AddField(
            model_name='crossword',
            name='down_words',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crossword',
            name='grid_blocks',
            field=models.TextField(default=''),
        ),
    ]
