# Generated by Django 4.2.2 on 2023-06-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('puzzles', '0008_cluessolved_groupsession_solvesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='open_at',
            field=models.DateTimeField(),
        ),
    ]
