# Generated by Django 4.2.2 on 2023-06-30 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0010_remove_groupsession_open_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed', models.BooleanField(default=False)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.clue')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.solvesession')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CluesSolved',
        ),
    ]
