# Generated by Django 4.2.2 on 2023-07-06 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0011_solvedclue_delete_cluessolved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolveSession',
            new_name='SolverSession',
        ),
    ]
