# Generated by Django 3.1.2 on 2020-10-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_auto_20201029_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
