# Generated by Django 3.1.2 on 2020-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_puzzle_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_xword',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
