# Generated by Django 3.1.2 on 2020-10-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_auto_20201029_0100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crossword',
        ),
    ]
