# Generated by Django 3.1.2 on 2020-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0014_delete_crossword'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
