# Generated by Django 3.1.2 on 2021-01-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0015_puzzle_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='is_ready',
        ),
    ]
