# Generated by Django 3.1 on 2022-01-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0015_puzzle_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='is_ready',
        ),
    ]
