# Generated by Django 3.1 on 2022-02-15 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0016_remove_puzzle_is_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Non-cryptic Clues'), (1, 'Cryptic Clues')], default=1)),
                ('size', models.IntegerField(default=0)),
                ('desc', models.TextField(null=True)),
                ('shared_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
