# Generated by Django 3.1 on 2022-02-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0017_wordpuzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_num', models.IntegerField()),
                ('answer', models.CharField(max_length=32, null=True)),
                ('clue_text', models.TextField(null=True)),
                ('parsing', models.TextField(null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.wordpuzzle')),
            ],
        ),
    ]
