# Generated by Django 3.1 on 2022-02-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0018_clue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpuzzle',
            name='size',
            field=models.IntegerField(default=5),
        ),
    ]
