# Generated by Django 3.1 on 2022-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0019_auto_20220217_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpuzzle',
            name='title',
            field=models.CharField(help_text='Optional short title to indicate theme etc', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clue_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clue_text',
            field=models.TextField(help_text='Do not include word length (automatically calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='parsing',
            field=models.TextField(help_text='Optional explanation of solution', null=True),
        ),
        migrations.AlterField(
            model_name='wordpuzzle',
            name='desc',
            field=models.TextField(help_text='Optional description, instructions or guidelines', null=True),
        ),
    ]
