# Generated by Django 3.1 on 2022-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0021_auto_20220221_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='points',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='clue',
            name='answer',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='clue_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='parsing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordpuzzle',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordpuzzle',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordpuzzle',
            name='title',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
