# Generated by Django 3.1 on 2022-02-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0022_auto_20220222_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpuzzle',
            name='title',
        ),
    ]
