# Generated by Django 3.1 on 2022-02-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0023_remove_wordpuzzle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpuzzle',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
